version: 2.1

orbs:
  architect: giantswarm/architect@2.7.0

jobs:
  build-binary:
    docker:
      - image: golang:1.14
    steps:
      - run: git clone https://github.com/coredns/coredns.git
      - checkout:
          path: plugin
      - run: ./plugin/patch-plugin.sh coredns plugin
      - run: cd coredns && make
      - run: ./coredns/coredns -version
      - save_cache:
          paths: 
            - coredns
          key: coredns-binary
      - persist_to_workspace:
          root: .
          paths:
            - ./coredns/coredns

workflows:
  test:
    jobs:
      - architect/go-test:
          name: go-test
          filters:
            # Trigger job also on git tag.
            tags:
              only: /^v.*/
      - build-binary
      - architect/push-to-docker:
          image: quay.io/giantswarm/coredns-malicious-domain-plugin
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-test
            - build-binary
          filters:
            # Trigger job also on git tag.
            tags:
              only: /^v.*/
