version: 2.1

orbs:
  architect: giantswarm/architect@2.7.0

jobs:
  build-binary:
    docker:
      - image: golang:1.14
    steps:
      - run: git clone https://github.com/coredns/coredns.git
      - run: ls coredns
      - checkout: plugin
      - run: ls plugin

workflows:
  test:
    jobs:
      - architect/go-test:
          name: go-test
          filters:
            # Trigger job also on git tag.
            tags:
              only: /^v.*/
      - build-binary
